### ISSUE TITLE
[Feature Request] Option to close any existing open frames when opening new one

### ISSUE THREAD

**Issue by tom-f-oconnell** [BadIdeasBureau/scene-viewer#4]
I just found this module and it's very helpful. I'm using it to preview maps from scene compendium packs, but it's a bit annoying having to close all preceding previews when clicking through a bunch to see what might work. There could be an option in the settings to enable this behavior.

I might work on a pull request later but I'm pretty unfamiliar with the tech involved and just wanted to get this out here in case I forget / don't get the time.

**Comment by BadIdeasBureau** [comment]
That sounds entirely doable. I've got next week off work, and planning to
spend a chunk of that on module work, so happy to implement this myself.

**Comment by BadIdeasBureau** [comment]
Added in latest commit.  Testing needed, but should be released tonight.

Minor incompatibility with Token HUD art viewer (and any other modules that make use of MultiMediaPopout by Zeel), as it will close those popouts as well.
