### ISSUE TITLE
[Minor Bug] TypeError when also using Combat Utility Belt

### ISSUE THREAD

**Issue by tom-f-oconnell** [BadIdeasBureau/scene-viewer#5]
I was poking around inside the Foundry builtin console, and noticed a lot of errors that seemed related to this module (I started looking through the code before you replied to my feature request, so I recognized `MultiMediaPopout`). It doesn't seem to affect my ability to use this module but it might still be worth explicitly doing nothing in case `entity` is `null`, just for the sake of having clean console output.

Relevant portion of the console contents:
```
foundry.js:4503 Foundry VTT | Rendering SettingsConfig
foundry.js:5956 Foundry VTT | Retrieved and compiled template templates/sidebar/apps/settings-config.html
foundry.js:5956 Foundry VTT | Retrieved and compiled template templates/app-window.html
foundry.js:4503 Foundry VTT | Rendering Compendium
foundry.js:5956 Foundry VTT | Retrieved and compiled template templates/apps/compendium.html
foundry.js:4503 Foundry VTT | Rendering Dialog
foundry.js:5956 Foundry VTT | Retrieved and compiled template templates/hud/dialog.html
foundry.js:4503 Foundry VTT | Rendering MultiMediaPopout
foundry.js:5956 Foundry VTT | Retrieved and compiled template modules/scene-viewer/templates/media-popout.html
foundry.js:2498 Foundry VTT | Error thrown in hooked function 
_call @ foundry.js:2498
call @ foundry.js:2481
_render @ foundry.js:4547
async function (async)
_render @ foundry.js:4509
_render @ foundry.js:5157
_render @ foundry.js:17711
async function (async)
_render @ foundry.js:17710
render @ foundry.js:4479
loadImage @ scene-viewer.js:73
(anonymous) @ scene-viewer.js:56
async function (async)
(anonymous) @ scene-viewer.js:54
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:2499 TypeError: Cannot read property 'entity' of null
    at Function._onRenderImagePopout (hide-npc-names.js:243)
    at signal.js:174
    at Function._call (foundry.js:2496)
    at Function.call (foundry.js:2481)
    at MultiMediaPopout._render (foundry.js:4547)
    at async MultiMediaPopout._render (foundry.js:5157)
_call @ foundry.js:2499
call @ foundry.js:2481
_render @ foundry.js:4547
async function (async)
_render @ foundry.js:4509
_render @ foundry.js:5157
_render @ foundry.js:17711
async function (async)
_render @ foundry.js:17710
render @ foundry.js:4479
loadImage @ scene-viewer.js:73
(anonymous) @ scene-viewer.js:56
async function (async)
(anonymous) @ scene-viewer.js:54
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

Using the module "Find the culprit!", I found that "Combat Utility Belt" was ultimately causing this issue in my case. I am using the most up-to-date versions of all modules / systems / stable Foundry (0.7.9).

Thanks again.

**Comment by BadIdeasBureau** [comment]
I believe that's a CUB issue, rather than something on my end (CUB is
checking for an actor associated with the window, and panicking when it
cant find any entity) - but I'll take a look and see if I can pass
something to make it not throw the error (might not be possible depending
on what it expects to find, since the entire point if this module is that
the scene is not loaded as an entity for everyone).

**Comment by tom-f-oconnell** [comment]
You could very well be right that it's just a CUB issue. I should also say that I encountered this once per attempt at loading a preview, though still I suppose it could just be on the CUB end. I didn't dig deep enough to really say.

**Comment by BadIdeasBureau** [comment]
Fixed on local version. Will push this out in a release tonight.
